defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
sass:
  sass_dir: _scss
  style: compressed
markdown: redcarpet
redcarpet:
  extensions: ["footnotes", "hard_wrap", "no_intra_emphasis", "autolink", "strikethrough"]
permalink: /:year/:month/:day/:title
exclude: ["gaelian.github.io.sublime-project", "Gemfile", "Gemfile.lock", "README.md"]
gems:
  - jekyll-redirect-from
